import Head from "next/head";
import { Inter } from "next/font/google";
import { signIn, signOut } from "next-auth/react";
import { useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data, status } = useSession();

  console.log(data, status);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <button onClick={() => signIn()}>Login</button>
        <button onClick={() => signOut()}>logout</button>
      </main>
    </>
  );
}
